In [40]:
import pandas as pd
import numpy as np
import time
import datetime

df = pd.read_csv('../../data/DataFrame_Final_Cierre_FullFecha.csv', parse_dates=['FECHA'])

In [46]:
test=df.groupby(by=['TEMPORADA', 'TEMPORADA_NUM']).count()
test

,,ESTACION,ANIO,MES,DIA,HORA,FECHA,DIA_SEMANA,AM_PM,Es_Festivo,Es_FinSemana,TEMPERATURA,VIENTO,PRESION,HUMEDAD,PRECIPITACION_1h,PRECIPITACION_3h,DESC_TIEMPO,DESC_TIEMPO_detalle,DEMANDA
TEMPORADA,TEMPORADA_NUM,,,,,,,,,,,,,,,,,,,
INVIERNO,1,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040
OTONO,4,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464
PRIMAVERA,2,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872
VERANO,3,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464

In [42]:
df['TEMPORADA_NUM'] = 0

In [43]:
df

,ESTACION,ANIO,MES,DIA,HORA,FECHA,DIA_SEMANA,AM_PM,TEMPORADA,Es_Festivo,...,TEMPERATURA,VIENTO,PRESION,HUMEDAD,PRECIPITACION_1h,PRECIPITACION_3h,DESC_TIEMPO,DESC_TIEMPO_detalle,DEMANDA,TEMPORADA_NUM
0,6,2018,1,1,0,2018-01-01 00:00:00,2,AM,INVIERNO,1,...,6.63,5.70,1031.0,56.0,0.0,0.0,Clear,sky is clear,2,0
1,6,2018,1,1,1,2018-01-01 01:00:00,2,AM,INVIERNO,1,...,6.47,5.70,1031.0,55.0,0.0,0.0,Clear,sky is clear,0,0
2,6,2018,1,1,2,2018-01-01 02:00:00,2,AM,INVIERNO,1,...,5.58,4.90,1031.0,60.0,0.0,0.0,Clear,sky is clear,2,0
3,6,2018,1,1,3,2018-01-01 03:00:00,2,AM,INVIERNO,1,...,6.58,7.20,1030.0,59.0,0.0,0.0,Clear,sky is clear,0,0
4,6,2018,1,1,4,2018-01-01 04:00:00,2,AM,INVIERNO,1,...,5.14,4.63,1032.0,57.0,0.0,0.0,Clear,sky is clear,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3393835,198,2020,2,29,19,2020-02-29 19:00:00,7,PM,INVIERNO,0,...,12.17,8.80,1013.0,60.0,0.0,0.0,Clouds,few clouds,0,0
3393836,198,2020,2,29,20,2020-02-29 20:00:00,7,PM,INVIERNO,0,...,11.49,8.80,1014.0,61.0,0.0,0.0,Clouds,few clouds,0,0
3393837,198,2020,2,29,21,2020-02-29 21:00:00,7,PM,INVIERNO,0,...,11.11,7.20,1014.0,67.0,0.0,0.0,Clouds,few clouds,0,0
3393838,198,2020,2,29,22,2020-02-29 22:00:00,7,PM,INVIERNO,0,...,10.31,6.20,1015.0,69.0,0.0,0.0,Clouds,few clouds,0,0
3393839,198,2020,2,29,23,2020-02-29 23:00:00,7,PM,INVIERNO,0,...,9.60,6.20,1015.0,69.0,0.0,0.0,Clouds,few clouds,3,0

In [44]:
df[df['TEMPORADA']=='INVIERNO']

,ESTACION,ANIO,MES,DIA,HORA,FECHA,DIA_SEMANA,AM_PM,TEMPORADA,Es_Festivo,...,TEMPERATURA,VIENTO,PRESION,HUMEDAD,PRECIPITACION_1h,PRECIPITACION_3h,DESC_TIEMPO,DESC_TIEMPO_detalle,DEMANDA,TEMPORADA_NUM
0,6,2018,1,1,0,2018-01-01 00:00:00,2,AM,INVIERNO,1,...,6.63,5.70,1031.0,56.0,0.0,0.0,Clear,sky is clear,2,0
1,6,2018,1,1,1,2018-01-01 01:00:00,2,AM,INVIERNO,1,...,6.47,5.70,1031.0,55.0,0.0,0.0,Clear,sky is clear,0,0
2,6,2018,1,1,2,2018-01-01 02:00:00,2,AM,INVIERNO,1,...,5.58,4.90,1031.0,60.0,0.0,0.0,Clear,sky is clear,2,0
3,6,2018,1,1,3,2018-01-01 03:00:00,2,AM,INVIERNO,1,...,6.58,7.20,1030.0,59.0,0.0,0.0,Clear,sky is clear,0,0
4,6,2018,1,1,4,2018-01-01 04:00:00,2,AM,INVIERNO,1,...,5.14,4.63,1032.0,57.0,0.0,0.0,Clear,sky is clear,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3393835,198,2020,2,29,19,2020-02-29 19:00:00,7,PM,INVIERNO,0,...,12.17,8.80,1013.0,60.0,0.0,0.0,Clouds,few clouds,0,0
3393836,198,2020,2,29,20,2020-02-29 20:00:00,7,PM,INVIERNO,0,...,11.49,8.80,1014.0,61.0,0.0,0.0,Clouds,few clouds,0,0
3393837,198,2020,2,29,21,2020-02-29 21:00:00,7,PM,INVIERNO,0,...,11.11,7.20,1014.0,67.0,0.0,0.0,Clouds,few clouds,0,0
3393838,198,2020,2,29,22,2020-02-29 22:00:00,7,PM,INVIERNO,0,...,10.31,6.20,1015.0,69.0,0.0,0.0,Clouds,few clouds,0,0
3393839,198,2020,2,29,23,2020-02-29 23:00:00,7,PM,INVIERNO,0,...,9.60,6.20,1015.0,69.0,0.0,0.0,Clouds,few clouds,3,0

In [45]:
df.loc[df['TEMPORADA']=='INVIERNO', 'TEMPORADA_NUM'] = 1
df.loc[df['TEMPORADA']=='PRIMAVERA', 'TEMPORADA_NUM'] = 2
df.loc[df['TEMPORADA']=='VERANO', 'TEMPORADA_NUM'] = 3
df.loc[df['TEMPORADA']=='OTONO', 'TEMPORADA_NUM'] = 4
df

,ESTACION,ANIO,MES,DIA,HORA,FECHA,DIA_SEMANA,AM_PM,TEMPORADA,Es_Festivo,...,TEMPERATURA,VIENTO,PRESION,HUMEDAD,PRECIPITACION_1h,PRECIPITACION_3h,DESC_TIEMPO,DESC_TIEMPO_detalle,DEMANDA,TEMPORADA_NUM
0,6,2018,1,1,0,2018-01-01 00:00:00,2,AM,INVIERNO,1,...,6.63,5.70,1031.0,56.0,0.0,0.0,Clear,sky is clear,2,1
1,6,2018,1,1,1,2018-01-01 01:00:00,2,AM,INVIERNO,1,...,6.47,5.70,1031.0,55.0,0.0,0.0,Clear,sky is clear,0,1
2,6,2018,1,1,2,2018-01-01 02:00:00,2,AM,INVIERNO,1,...,5.58,4.90,1031.0,60.0,0.0,0.0,Clear,sky is clear,2,1
3,6,2018,1,1,3,2018-01-01 03:00:00,2,AM,INVIERNO,1,...,6.58,7.20,1030.0,59.0,0.0,0.0,Clear,sky is clear,0,1
4,6,2018,1,1,4,2018-01-01 04:00:00,2,AM,INVIERNO,1,...,5.14,4.63,1032.0,57.0,0.0,0.0,Clear,sky is clear,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3393835,198,2020,2,29,19,2020-02-29 19:00:00,7,PM,INVIERNO,0,...,12.17,8.80,1013.0,60.0,0.0,0.0,Clouds,few clouds,0,1
3393836,198,2020,2,29,20,2020-02-29 20:00:00,7,PM,INVIERNO,0,...,11.49,8.80,1014.0,61.0,0.0,0.0,Clouds,few clouds,0,1
3393837,198,2020,2,29,21,2020-02-29 21:00:00,7,PM,INVIERNO,0,...,11.11,7.20,1014.0,67.0,0.0,0.0,Clouds,few clouds,0,1
3393838,198,2020,2,29,22,2020-02-29 22:00:00,7,PM,INVIERNO,0,...,10.31,6.20,1015.0,69.0,0.0,0.0,Clouds,few clouds,0,1
3393839,198,2020,2,29,23,2020-02-29 23:00:00,7,PM,INVIERNO,0,...,9.60,6.20,1015.0,69.0,0.0,0.0,Clouds,few clouds,3,1

In [47]:
test=df.groupby(by=['TEMPORADA', 'TEMPORADA_NUM']).count()
test

,,ESTACION,ANIO,MES,DIA,HORA,FECHA,DIA_SEMANA,AM_PM,Es_Festivo,Es_FinSemana,TEMPERATURA,VIENTO,PRESION,HUMEDAD,PRECIPITACION_1h,PRECIPITACION_3h,DESC_TIEMPO,DESC_TIEMPO_detalle,DEMANDA
TEMPORADA,TEMPORADA_NUM,,,,,,,,,,,,,,,,,,,
INVIERNO,1,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040,1031040
OTONO,4,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464
PRIMAVERA,2,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872,781872
VERANO,3,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464,790464

In [49]:
# REORDENAMIENTO DE COLUMNAS PREVIO A EXPORT

data_final_cierre = df[['ESTACION', 'ANIO', 'MES', 'DIA', 'HORA', 'FECHA', 'DIA_SEMANA', 'AM_PM', 'TEMPORADA', 'TEMPORADA_NUM', 'Es_Festivo', 'Es_FinSemana', 
                    'TEMPERATURA', 'VIENTO', 'PRESION', 'HUMEDAD', 'PRECIPITACION_1h', 'PRECIPITACION_3h', 'DESC_TIEMPO', 
                    'DESC_TIEMPO_detalle', 'DEMANDA']]
data_final_cierre

,ESTACION,ANIO,MES,DIA,HORA,FECHA,DIA_SEMANA,AM_PM,TEMPORADA,TEMPORADA_NUM,...,Es_FinSemana,TEMPERATURA,VIENTO,PRESION,HUMEDAD,PRECIPITACION_1h,PRECIPITACION_3h,DESC_TIEMPO,DESC_TIEMPO_detalle,DEMANDA
0,6,2018,1,1,0,2018-01-01 00:00:00,2,AM,INVIERNO,1,...,0,6.63,5.70,1031.0,56.0,0.0,0.0,Clear,sky is clear,2
1,6,2018,1,1,1,2018-01-01 01:00:00,2,AM,INVIERNO,1,...,0,6.47,5.70,1031.0,55.0,0.0,0.0,Clear,sky is clear,0
2,6,2018,1,1,2,2018-01-01 02:00:00,2,AM,INVIERNO,1,...,0,5.58,4.90,1031.0,60.0,0.0,0.0,Clear,sky is clear,2
3,6,2018,1,1,3,2018-01-01 03:00:00,2,AM,INVIERNO,1,...,0,6.58,7.20,1030.0,59.0,0.0,0.0,Clear,sky is clear,0
4,6,2018,1,1,4,2018-01-01 04:00:00,2,AM,INVIERNO,1,...,0,5.14,4.63,1032.0,57.0,0.0,0.0,Clear,sky is clear,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3393835,198,2020,2,29,19,2020-02-29 19:00:00,7,PM,INVIERNO,1,...,1,12.17,8.80,1013.0,60.0,0.0,0.0,Clouds,few clouds,0
3393836,198,2020,2,29,20,2020-02-29 20:00:00,7,PM,INVIERNO,1,...,1,11.49,8.80,1014.0,61.0,0.0,0.0,Clouds,few clouds,0
3393837,198,2020,2,29,21,2020-02-29 21:00:00,7,PM,INVIERNO,1,...,1,11.11,7.20,1014.0,67.0,0.0,0.0,Clouds,few clouds,0
3393838,198,2020,2,29,22,2020-02-29 22:00:00,7,PM,INVIERNO,1,...,1,10.31,6.20,1015.0,69.0,0.0,0.0,Clouds,few clouds,0
3393839,198,2020,2,29,23,2020-02-29 23:00:00,7,PM,INVIERNO,1,...,1,9.60,6.20,1015.0,69.0,0.0,0.0,Clouds,few clouds,3

In [50]:
data_final_cierre.to_csv('../../data/DataFrame_Final_Cierre_FullFecha.csv', index=False)